import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";
import ClientApplication from "./clientApplication";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yen's Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ClientApplication>
          <div className="bg-radial-from-center min-h-screen">
            <NavBar />
            {children}
            <Footer />
          </div>
        </ClientApplication>
      </body>
    </html>
  );
}
