import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";
import ClientApplication from "./clientApplication";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yen's Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ClientApplication>
          <div className="bg-radial-from-center min-h-screen">
            <NavBar />
            <main className="flex flex-col items-center justify-between p-4 lg:p-16 text-white">
              {children}
            </main>
            <Footer />
          </div>
        </ClientApplication>
      </body>
    </html>
  );
}
